### ISSUE TITLE
The contributing guide seems to be a little over-detailed

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#128]
1. Hi, I would like to discuss about the contributing guide. I personally find it a bit over-detailed on some aspects. For example, I am not sure it's a good idea to include a git-crash course in the file (I know scikit-learn did it, but not a big fan of that). Or probably we can keep all the detailed steps, but maybe we can split them into several pages + a table of content (just to make it more reader-friendly)? 
2.  A minor point: what are those (contributing)= lines in the file? Are they there for some reason?

**Comment by TimotheeMathieu** [comment]
Yes, I copied most of the scikit-learn page so it may be over-detailed for rlberry given that our project is smaller than scikit-learn. Maybe we can remove some of it.

about your two points: 

1. Let us ask some beginners about this  I think it would be nice to have your opinion on what sort of info should be in the guide @AleShi94, @riccardodv ? Personally I used the scikit-learn git crash-course a lot when I began contributing so I'm in favor of keeping it.
2. the (contributing)= line is an anchor for linking in markdown (same as .... _contributing: in rst). It is the name you have to use if you want to link to the contributing page.

**Comment by riccardodv** [comment]
I think that, since rlberry is meant for learning and research, we keep as many details as possible. In this way, people can also learn how to contribute even if they have never done it before. So, I am in favour of keeping all the detailed steps, but as @xuedong  said, maybe we can split them into several pages + a table of content.

**Comment by AleShi94** [comment]
Hi, I agree with @xuedong that for now there is too much information on one page. At the same time I find that all of this is useful, but it will be more convenient if it was broken into several pages or if we have a table of content somewhere indeed. Maybe we should also make "how to install" the separate page, for now it is in "how to contribute". Otherwise, in general to improve readability we can use more key words. They can be used as "captions" for the bullet point items, put in bold, for example?

**Comment by xuedong** [comment]
Improved with #150 , close the issue
