### ISSUE TITLE
gym0.21 fork and installation instructions

### ISSUE THREAD

**Issue by omardrwch** [rlberry-py/rlberry#321]
Hello! If I understood correctly, we need to install gym from the forked 0.21 version. However, it is not mentioned in the README or in the documentation page (https://github.com/rlberry-py/rlberry/blob/main/docs/installation.rst).

**Comment by TimotheeMathieu** [comment]
Yes, this is a problem with setuptools, we propose one solution but in fact there are several solutions. 

We did not want to bother too much with it because the goal is to release a new version in the next few days with gymnasium merged. The idea is that v0.4.1 will be the last gym version and then we switch directly to v0.4.2 in gymnasium in order to have something easily installable with pip (the problem is that pypi does not want us to specify a dependency with a git repo so we can't say that it depends on our fork of gym0.21).

**Comment by omardrwch** [comment]
I see, thank you!
