### ISSUE TITLE
Bandits

### ISSUE THREAD

**Issue by TimotheeMathieu** [rlberry-py/rlberry#71]
Here is another brainstorming issue.

There have been a proposition of coding bandits in RLBerry. The idea would be to 
* Facilitate parallel computing, logging and plots. 
* Have some benchmark (for bandits and for environments)
  * Classical bandits algo, environments, and metrics
  * Possible inspiration : https://github.com/tensorflow/agents/tree/master/tf_agents/bandits
  * Clear and easily changed code. Modular code, for the user to be able to change just one little thing without rewriting everything.
* Have Benchmark datasets/environments
* Have environment for corrupted, differentially private, fair bandits

Questions are : 
* Whether we go with it and do a bandit module ? 
* Guidelines of this bandit module ? (simplicity for the user, readability...)
* There are a lot of algo/environments. We could say that (similarly to scikit-learn) we include only algo that have been cited a certain number of times and something similar for the environment ?

**Comment by mmcenta** [comment]
Hi,

I think supporting bandits as well as RL is a great idea since there are a lot of people working with bandits here at the lab. However, I don't think we should focus too much on modularity for now because it should be compatible with whatever we decide to do for RL algorithms. I think a good initial scope for this module is:

- Provide bandit implementations that are compatible with rlberry's current code (using Agents);
- Provide benchmark implementations (maybe someplace else? see issue #74);

As for guidelines,

- In terms of simplicity, I'd try to match rlberry's current philosophy by providing something similar to an `AgentWithSimplePolicy class for bandits and then implementing baseline algorithms using it;
- Easy to understand code: this is a research library, people should be able to easily understand the implementation and change it if necessary (maybe modularity is not that important here because bandit implementations are usually already small);

Finally, I am not very familiar with the bandit literature, so I don't know what would be a good criterion to decide whether an algorithm/environment should be included. I do think that this problem can be at least partially solved by putting less essential stuff in another repository (as per issue #74, again).
