### ISSUE TITLE
Support environments on rlberry?

### ISSUE THREAD

**Issue by mmcenta** [rlberry-py/rlberry#74]
Currently, rlberry supports [some environments](https://github.com/rlberry-py/rlberry/tree/main/rlberry/envs), but we would like to add other environments developed by the SCOOL group to the repository. This raises the question of whether we should have environments as part of rlberry or not. An alternative would be to create another repository (like an RL Baselines Zoo for rlberry) in which we would put code for the environments (and possibly other things such as default hyperparameters). 

I think it would be cleaner to separate the two repositories so that we can keep rlberry concise. In that case, we would still need to:

1. Decide what things will go into this new repository (trained agents, default hyperparameters, etc..)
2. Give the new repository a name
3. Create issues to remove what isn't needed here

**Comment by omardrwch** [comment]
Since one of the principles of the library is to help people design their agents, and environments are a key part of algorithmic design, I think it is important to keep environments in `rlberry`, but **not all** environments.

For instance, grid worlds (continuous or discrete) are very useful to debug agents, and I think that environments for debugging/analysis of agents should not only be kept, but developed.

However, I think that application-specific environments (as some that are developed by the team to simulate crops, for instance) should be kept in another repository, because their purpose is to solve a specific applied problem, rather than helping people to debug/develop general agents.

To summarize:
* I suggest to keep and develop simple environments for debugging;
* and to put application-specific environments (and that are more complex) in another repository.

Some other points that are useful in rlberry environments:
*  `rlberry` provides tools for users to easily render their own 2D environments (`rlberry.rendering`, which we can extend to 3D), and visualization is very useful for debugging;
* `rlberry` provides an interface for environments that represent a generative model, that is, with a method `sample(state, action)` to collect a transition from any (state, action) pair; in addition to a `step(action)` that only takes an `action`. Some RL algorithms require a generative model, and might be implemented in `rlberry`, so we need to keep this environment interface in the library anyway.
