### ISSUE TITLE
Some minor questions about readthedocs

### ISSUE THREAD

**Issue by xuedong** [rlberry-py/rlberry#80]
Hello guys, some minor questions about the doc:

1). Is the following numbering 2, 1, 2, 1 expected?

<img width="470" alt="Screen Shot 2021-12-01 at 17 28 19" src="https://user-images.githubusercontent.com/1488899/144283903-c4a462f5-5315-4175-87ec-c4b6fee03b27.png">

2). When clicked on the cite us button, it is showing not found as below
<img width="1263" alt="Screen Shot 2021-12-01 at 17 33 25" src="https://user-images.githubusercontent.com/1488899/144284389-9deccc91-a562-47cf-b505-76986abc06c1.png">

3). Not very important, but more aesthetic question, I find it a bit disturbing when things are spread out on two lines 
<img width="231" alt="Screen Shot 2021-12-01 at 17 35 02" src="https://user-images.githubusercontent.com/1488899/144284640-2e63a816-8d8a-4cb8-8769-ca184e04ce2f.png">

**Comment by TimotheeMathieu** [comment]
`1). Is the following numbering 2, 1, 2, 1 expected?`
No, I fixed it in PR #77 

`2). When clicked on the cite us button, it is showing not found as below`
I will fix this

`3). Not very important, but more aesthetic question, I find it a bit disturbing when things are spread out on two lines`
Are you talking about the "cite us" box or the menu ? I can : increase the horizontal size of the menu, replace the sentence with the "cite us" with a shorter sentence, and I can add space between two items in the menu in order to have a cleaner look. What solution do you think is the best ?

**Comment by xuedong** [comment]
Sorry, was not very clear for Q3, was talking about items in the menu. Yes, probably we can increase the spaces between items first to see how it looks.
